#This program is a madlib format story
#
#Tatem Pearson
#August 27, 2017

print("Hello this is a madlib program.")
print("Before we get started let me ask you a couple of questions.")
print("First what is your name?")
name = input()
print("Thank you for testing my program, " + name + ".")
print("This madlib story will be about you and two friends.")
print("Pick any two people you want to insert into the story.")
friend1 = input()
friend2 = input() 
print("And now we can begin.")
print("It was a/an ADJECTIVE day at J.L. Mann. When out of nowhere something was amiss.")
adj1 = input()
print("It was a/an " + adj1 + " day at J.L. Mann. When out of nowhere something was amiss.")
print(name + " had forgotten his/her homework!")
print(name + " turned ADJECTIVE in panic. his/her friend, " +friend1+ " noticed " + name + "'s expression.")
adj2 = input()
print(name + " turned " + adj2 + " in panic. his/her friend, " +friend1+ " noticed " + name + "'s expression.")
print("The teacher was walking ADVERB collecting homework, quickly approaching." + name + "'s NOUN.")
adv1 = input()
noun1 = input()
print("The teacher was walking " + adv1 + " collecting homework, quickly approaching " + name + "'s " + noun1 + ".")
print(name + " turned to " + friend2 + " only to realize he/she was VERB and there was no homework on his/her desk either.")
v1 = input()
print(name + " turned to " + friend2 + " only to realize he/she was " + v1 + " and there was no homework on his/her desk either.")
print(friend1 + " had already turned in his/her homework. " + name + " turned around to see CELEBRITY behind him/her.")
celeb1 = input()
print(friend1 + " had already turned in his/her homework. " + name + " turned around to see " + celeb1 + " behind him/her.")
print(name + " exclaimed to " +friend1 + " and " + friend2 + " that the ADJ and ADJ " + celeb1 + " was in the classroom.")
adj3 = input()
adj4 = input()
print(name + " exclaimed to " +friend1 + " and" + friend2 + " that the " + adj3 + " and " + adj4 + celeb1 + " was in the classroom.")
print(celeb1 + " was " + name + "'s " " only hope now. " + name + " VERB to " + celeb1 + " and he/she replied with, WRITE SOMETHING FOR " + celeb1 + " TO SAY. ")
v2 = input()
speech = input() 
print(celeb1 + " was " + name + "'s " " only hope now. " + name + v2 + "ed to " + celeb1 + " and he/she replied with, " + speech)
print(celeb1 + " let " + name + " copy their homework. " + friend1 + " and " + friend2 + " were ADJ that " + name + " was able to copy " + celeb1 + "'s homework. the once " + adj1 + " day turned into a/an ADJ day.")
adj5 = input()
adj6 = input() 
print(celeb1 + " let " + name + " copy their homework. " + friend1 + " and " + friend2 + " were " + adj5 + " that " + name + " was able to copy " + celeb1 + "'s homework. the once " + adj1 + " day turned into a/an " + adj6 + "day.")
print("Thank you for testing my madlib, " + name + "!") 
